- src/events/event-generator.ts
- src/events/pattern-uploader.ts
- src/webview/chat_css.ts
- src/webview/chat_html.ts
- src/webview/chat_js.ts
Hello @olasunkanmi-SE ,
I have made a PR for this issue https://github.com/olasunkanmi-SE/codebuddy/issues/54 & https://github.com/olasunkanmi-SE/codebuddy/issues/48
Here are the changes I have implemented:
**Copy Button for Code:** Added a copy button to code snippets, allowing users to easily copy code with a single click.
**Scroll Down Button:** Implemented a scroll down button to quickly navigate to the latest content in the interface.
Here is a screenshot of the updated interface:
Please let me know if this feature aligns with the project's goals, and I'd be happy to work on it.
Thank you!
> Issue #54 & #48 Copy button and Scroll down button

- package.json
- src/constant.ts
- src/events/event-generator.ts
- src/events/inline-chat.ts
- src/extension.ts
- src/providers/code-actions-provider.ts
- src/providers/groq-web-view-provider.ts
- src/services/chat-manager.ts
- Introduce new InLineChat class for handling in-line chat interactions
- Update EventGenerator to support in-line chat functionality 
- Add new command for in-line chat in package.json and extension.ts Modify existing code to accommodate in-line chat changes
> feat(api, ui): Add in-line chat functionality

- package-lock.json
- package.json
- src/application/constant.ts
- src/extension.ts
- src/infrastructure/repository/code-repository.ts
- src/infrastructure/repository/sql.ts
- src/services/code-structure.mapper.service.ts
- src/services/context-service.ts
- src/services/embedding-service.ts
- src/services/typescript-ats.service.ts
- Add embedding service with Xenova transformers for vector embeddings
- Implement context service for code indexing and function mapping
- Configure embedding settings with batch processing and rate limiting
- Update code repository to separate table creation and data insertion
- Add @xenova/transformers dependency
- Refactor TypeScriptAtsMapper to use singleton pattern
> Create repository and code mapper

- src/agents/orchestrator.ts
- src/commands/event-generator.ts
- src/emitter/agent-emitter.ts
- src/emitter/emitter.ts
- src/extension.ts
- src/infrastructure/storage/local-storage.ts
- src/memory/base.ts
- src/providers/anthropic.ts
- src/providers/gemini.ts
- src/providers/groq.ts
- src/services/generative-ai-model-manager.ts
- src/utils/utils.ts
- Improve type safety and reusability in BaseEmitter
- Introduce LocalStorageManager for secure data storage
> Improve type safety and reusability in BaseEmitter

- src/agents/agent.ts
- src/agents/orchestrator.ts
- src/emitter/agent-emitter.ts
- src/emitter/interface.ts
- src/providers/anthropic.ts
- src/providers/base.ts
- src/providers/gemini.ts
- src/providers/groq.ts
- webviewUi/src/components/webview.tsx
- Update agent interface to include new query handling functionality 
- Modify Orchestrator to handle new query events
- Adjust providers to use the updated CodeBuddy agent Implement processInput method in provider classes
- Update event emitter to include onPrompt event
- Add query status to EventState type
> Rename TextAnalysisAgent to CodeBuddy for better clarity

- src/agents/orchestrator.ts
- src/emitter/agent-emitter.ts
- src/emitter/emitter.ts
- src/emitter/interface.ts
- src/llms/gemini/gemini.ts
- src/llms/interface.ts
- src/llms/message.ts
- src/providers/anthropic.ts
- src/providers/base.ts
- src/providers/gemini.ts
- src/providers/groq.ts
- src/utils/llm-config-validator.ts
- Introduce a  class to encapsulate chat message details (role, content, parts).
- Refactor Anthropic, Gemini and Groq providers to utilize the  class for managing chat history.
- Update chat history management in , , and  to use  instances.
> feat(llms): Introduce Message class for structured chat history

- src/infrastructure/logger/logger.ts
- src/llms/base.ts
- src/llms/gemini/gemini.ts
- src/llms/message.ts
- src/providers/gemini.ts
- src/utils/llm-config-validator.ts
- Implement chat history for Gemini model to maintain context across conversations
- Improve error handling in logger and LLM configuration validation
- Refactor Gemini LLM to use a singleton instance
- Update message handling to use content or parts, but not both
> feat(gemini): implements chat history and improve error handling

- src/application/interfaces/agent.interface.ts
- src/providers/tool.ts
- src/services/context-retriever.ts
- src/tools/base.ts
- src/tools/database/search-tool.ts
- src/tools/search/googleSearch.ts
- Add CodeBuddyTool base class and related interfaces 
- Implement ToolFactory and CodeBuddyToolProvider for tool management 
- Create ContextRetriever service for retrieving similar code contexts 
- Add SearchTool as the first CodeBuddyTool 
- implementation Remove unused sql.ts file and update GoogleSearchTool
> feat(tools): implement CodeBuddyTool system and ContextRetriever

- package-lock.json
- package.json
- src/agents/architecture.md
- src/agents/orchestrator.ts
- src/llms/gemini/gemini.ts
- webviewUi/src/components/botMessage.tsx
- webviewUi/src/components/webview.tsx
- webviewUi/src/index.css
- Adds  for sanitizing HTML content to prevent XSS vulnerabilities.
- Integrates  for syntax highlighting in code blocks.
- Creates a new  file containing a Mermaid diagram illustrating the system's architecture.
- Removes isLoading state from webview.tsx
> feat(ui): Enhance code block display and add architecture documentation

- src/llms/gemini/gemini.ts
- src/providers/base.ts
- src/providers/tool.ts
- src/services/context-retriever.ts
- src/services/web-search-service.ts
- src/tools/tools.ts
- src/utils/prompt.ts
- Integrates web search capability to enhance information retrieval.
- Handle web queries and content extraction.
- allow agents to utilize web search.
- Updates to include web search functionality.
> feat: Add web search functionality

- src/agents/orchestrator.ts
- src/emitter/agent-emitter.ts
- src/emitter/interface.ts
- src/extension.ts
- src/providers/base.ts
- src/providers/secret-storage-provider.ts
- src/services/typescript-ats.service.ts
- Introduces  to securely store and retrieve secrets using VS Code's secret storage.
- Implements  to listen for secret changes and trigger  event.
- Adds  and  events to  and .
- Modifies  to handle  events.
- Updates  to set code index in Memory.
> feat: Add secret storage provider and event handling

- README.md
- src/providers/webview-events-provider.ts
- src/webview/chat_html.ts
- webviewUi/index.html
- webviewUi/src/components/webview.tsx
- webviewUi/src/utils/highlightCode.ts
- Enhance code block highlighting with language detection and HTML decoding
- Add a Copy button to code blocks for easy copying to clipboard
- Improve error handling during code highlighting and copy operations
- Move highlight.js script tag to the head in chat_html.ts
- Remove unused Ttopic types
> feat(webview): Improve code highlighting and add copy functionality

- src/commands/event-generator.ts
- src/extension.ts
- src/llms/gemini/gemini.ts
- src/providers/base.ts
- src/providers/gemini.ts
- src/services/web-search-service.ts
- src/utils/prompt.ts
- src/utils/utils.ts
- src/webview/chat_html.ts
- webviewUi/src/components/botMessage.tsx
- webviewUi/src/components/urlCardList.tsx
- webviewUi/src/index.css
- webviewUi/src/utils/highlightCode.ts
- webviewUi/src/utils/parseUrl.ts
- Fetch favicon and title for search result URLs to provide richer context.
- Display extracted metadata, including favicon, title, and URL, in the chat interface using a new UrlCardList component.
- Implement UI improvements for displaying web search results.
> feat(web-search): Enhance web search results with metadata

- src/utils/prompt.ts
- webviewUi/src/components/webview.tsx
- webviewUi/src/index.css
- Introduces a tabbed interface using VSCodePanels for chat, history, settings, and other functionalities.
- Implements state management for active tabs.
- Modifies the layout to accommodate the tabbed interface, ensuring proper height and overflow handling.
- Moves the User Query to the end of the prompt so the instruction appears before the query.
- Updates textarea styling to use VSCodeTextArea for better integration with VS Code themes.
> feat(ui): Implement tabbed interface and improve prompt handling

- webviewUi/src/index.css
- Update CSS to ensure elements adapt to different screen sizes.
- Remove fixed widths to allow flexible scaling.
> style(ui): Adjust UI elements for better responsiveness

- package.json
- src/services/workspace-service.ts
- webviewUi/src/components/context.tsx
- webviewUi/src/components/webview.tsx
- webviewUi/src/index.css
This commit introduces an attachment selector component in the webview UI.
- Implement AttachmentSelector component with dropdown for selecting context items.
- Add support for hierarchical categories and breadcrumb navigation.
- Integrate AttachmentSelector into the input area of the webview.
> feat(ui): Implement attachment selector for context insertion

- src/application/interfaces/workspace.interface.ts
- src/extension.ts
- src/providers/base.ts
- src/services/workspace-service.ts
- webviewUi/src/components/context.tsx
- webviewUi/src/components/errorBoundry.tsx
- webviewUi/src/components/errorFallBack.tsx
- webviewUi/src/components/webview.tsx
- webviewUi/src/main.tsx
This commit introduces several improvements to the webview, including better workspace context handling and robust error boundaries.
- Implement workspace folder structure retrieval and display in the webview, enabling users to navigate their project files.
- Add a new error boundary component to catch and display errors gracefully, improving the user experience.
- Enhance workspace selector to dynamically render the workspace context instead of a static list.
- Add UUID to workspace interface for proper identification of files.
> feat(webview): Enhance workspace context and add error handling

- src/providers/base.ts
- src/services/workspace-service.ts
- webviewUi/src/components/context.tsx
- webviewUi/src/components/webview.tsx
- webviewUi/src/index.css
- Improves the workspace context selector with better interaction and display of workspace folders.
- Enhances the UI layout for better user experience, including adjustments to the positioning of the input area.
- Updates styling for input fields to better match the VS Code theme.
> feat(ui): Enhance workspace context selector and UI layout

- package.json
- src/commands/knowledge-base.ts
- src/emitter/agent-emitter.ts
- src/extension.ts
- src/providers/base-web-view-provider.ts
- src/providers/base.ts
- src/providers/gemini.ts
- src/services/file-manager.ts
- src/services/file-system.ts
- src/services/workspace-service.ts
- webviewUi/src/App.css
- webviewUi/src/components/context.tsx
- webviewUi/src/components/webview.tsx
- webviewUi/src/index.css
- Integrate FileManager for handling knowledge base files, replacing FileUploader.
- Update knowledge base reading to use FileManager.
- Add codeBuddy logo to the chat view.
- Implement UI improvements, including minor changes in styles and component structure.
> feat(core): Enhance knowledge base integration and UI improvements

- src/emitter/agent-emitter.ts
- src/emitter/interface.ts
- src/providers/base.ts
- src/tools/tools.ts
- src/utils/prompt.ts
- webviewUi/index.html
- webviewUi/src/components/webview.tsx
- webviewUi/src/themes/tokyo-night.ts
- Adds a Think tool to the agent's capabilities, allowing it to structure complex problems and plan multi-step solutions.
- Updates prompt instructions to emphasize the strategic use of the Think tool before taking action in complex scenarios.
- Modifies tool descriptions to improve clarity and provide more specific guidance on when to use each tool.
- Introduces  event to emitter to trigger new logic.
> feat(ui): Introduce Think tool for complex problem-solving

- src/tools/tools.ts
- Fix ThinkTool config to use ThinkTool instead of WebTool.
> Fix(tools): Correct ThinkTool configuration

- src/llms/gemini/gemini.ts
- src/llms/groq/groq.ts
- webviewUi/src/components/webview.tsx
- webviewUi/src/constants/constant.ts
- Enhance the tool call processing in GeminiLLM to better handle function results and planning.
- Update the prompt construction to include plan information when available.
- Implement retry mechanism with user prompt for failed function calls with fallback to Groq.
- Add timeout mechanism for generateContentWithTools and fallback to Groq on timeout.
- Change the default CodeBuddy mode to Ask.
> feat(gemini): Improve tool call processing and error handling

- src/llms/gemini/gemini.ts
- Modify tool call processing to correctly handle and pass results.
- Ensure proper handling of the 'think' function and subsequent steps.
- Refactor the response structure for tool execution results.
- Add logic to break the loop when no function calls are returned.
- Publish the final query to the orchestrator for external monitoring.
> fix(gemini): Improve tool call handling and result processing

- src/agents/interface.ts
- src/application/constant.ts
- src/extension.ts
- src/infrastructure/storage/local-storage.ts
- src/llms/gemini/gemini.ts
- src/providers/gemini.ts
- src/services/agent-state.ts
- src/services/error.ts
- src/services/file-storage.ts
- src/services/telemetry.ts
- webviewUi/src/index.css
- Add AgentState interface to define the structure for agent-related information
- Implement AgentService to manage agent state, chat history, and snapshots using file storage
- Introduce AppError and related utilities for robust error handling and retryable operations
> feat(agents): Introduce agent state management and error handling

- src/application/constant.ts
- src/emitter/interface.ts
- src/extension.ts
- src/llms/gemini/gemini.ts
- src/services/code-indexing.ts
- src/services/context-retriever.ts
- src/services/url-reranker.ts
- src/utils/utils.ts
- src/webview-providers/base.ts
- src/webview-providers/groq.ts
- src/webview-providers/manager.ts
- webviewUi/src/components/select.tsx
- webviewUi/src/components/webview.tsx
- webviewUi/src/constants/constant.ts
- Updates the getAPIKeyAndModel function to retrieve both the API key and model name from configuration.
- Modifies the model selection process in the webview to send the selected model to the extension.
- Refactors the WebViewProviderManager to handle model changes and switch providers based on the selected model.
- Fixes an issue where the webview provider was not being registered correctly.
- Updates max_tokens for groq config.
> feat(core): Enhance model selection and API key retrieval

- webviewUi/src/components/webview.tsx
- webviewUi/src/index.css
- Introduces a visual representation of selected contexts using icons.
- Updates the UI to map the selected contexts to display them as icons.
- Adjusts the styling of hr elements for better visual appearance.
> feat(ui): Display selected contexts as icons

- src/emitter/interface.ts
- src/emitter/publisher.ts
- src/extension.ts
- src/services/chat-history-manager.ts
- src/services/file-system.ts
- src/services/file-watcher.ts
- src/webview-providers/base.ts
- webviewUi/src/components/context.tsx
- webviewUi/src/components/webview.tsx
This commit introduces a file watcher service that monitors file system events within the workspace.
- Add file watcher service to track file creation, renaming, deletion, and saving.
- Publish events for file creation, renaming, deletion, and saving.
- Update event emitter interface to include file system events.
> feat(file-watcher): Implement file system event monitoring

- README.md
- Refine the project structure description in README.md.
- Clarify the purpose of each directory.
- Update naming for better readability.
> docs(readme): Update project structure in README

- .vscode/settings.json
- package.json
- src/emitter/interface.ts
- src/emitter/publisher.ts
- src/services/secret-storage.ts
- src/webview-providers/base.ts
- webviewUi/src/components/webview.tsx
- Add new event types for user preferences management (onUpdateUserPreferences, onGetUserPreferences) 
- Implement user preferences persistence in SecretStorageService
-  Add username input and save functionality in webview UI Improve configuration handling with better documentation and methods
-  Rename Mermaid diagram command to be more descriptive Update VS Code settings with new theme and font configurations
> feat(user-preferences): add user preferences management

- CHANGELOG.md
- package.json
- Update CHANGELOG.md with comprehensive release notes for v2.0.0 Document major features including codebase understanding, AI agents, and UI improvements Organize changes into sections for AI intelligence, UI enhancements, functionality, and code improvements Bump version number from 1.2.3 to 2.0.0 in package.json
> chore(release): update to version 2.0.0

- IMPLEMENTATION_SUMMARY.md
- src/commands/review-pr.ts
- src/services/analysis-strategies/analysis-strategy-factory.ts
- src/services/analysis-strategies/api-endpoint-strategy.ts
- src/services/analysis-strategies/base-analysis-strategy.ts
- src/services/analysis-strategies/data-model-strategy.ts
- src/services/codebase-analysis-cache.ts
- src/services/codebase-understanding.service.ts
- src/services/input-validator.ts
- src/test/suite/codebase-analysis-cache.test.ts
- src/test/suite/codebase-understanding-cache.test.ts
- src/test/suite/codebase-understanding.test.ts
- src/webview-providers/base.ts
- Implement input validation to protect against prompt injection and XSS attacks.
- Introduce intelligent caching system to improve performance by avoiding expensive re-analysis.
- Refactor codebase analysis using strategy pattern for better separation of concerns and extensibility.
- Improve PR review system with VS Code git API integration and fallback mechanisms.
- Add comprehensive unit tests for input validation, caching, and strategy pattern functionality.
> feat(core): Enhance security, performance, and architecture
